version: "2.3.3"

services: 
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE} 
    ports:
      - "${DB_PORT}:${DB_PORT}"
  app: 
    build: .
    depends_on:
      - db
    command: yarn start
    ports: 
      - "3333:3333"
    volumes:
      - .:/usr/app
